---
# -----------------------------
# DISCO PERSISTENTE (PVC)
# -----------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi # Reservando 5GB do seu NVMe para arquivos e db.json

---
# -----------------------------
# BACKEND (NODE.JS)
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: node-backend-svc
spec:
  selector:
    app: node-backend
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: node-backend
          # Corrigido para o seu usuário e nome do repositório
          image: ghcr.io/raphacbs/node-backend:latest
          ports:
            - containerPort: 3000
          
          # --- MAPEAMENTO DAS PASTAS NO DISCO ---
          volumeMounts:
            - name: backend-storage
              mountPath: /app/data
              subPath: data
            - name: backend-storage
              mountPath: /app/uploads
              subPath: uploads
              
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
              
      # --- DECLARAÇÃO DO VOLUME VINCULADO AO PVC ---
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: node-backend-pvc